### ISSUE TITLE
Does this work on Lenovo Yoga Slim 7 intel version ? 

### ISSUE THREAD

**Issue by Pratham16112002** [HonusDaniel/yoga-slim-7-manager#2]

**Comment by dhonus** [comment]
Hello, I don't have an intel version to test on, but it should work just fine. You can safely try the script.

The power modes (low perf/balance/performance) will definitely work.

The battery conservation should work, but it may be in a different location. To make sure the battery charging limit works you can look if this file exists:
`/sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode`

if not, there will be a different directory in `/sys/bus/platform/drivers/ideapad_acpi`. This is where your battery control file will be.

**Comment by Pratham16112002** [comment]
Thanks, it is working on the intel version too, I think you must add in the readme that it is working on the intel version also.

**Comment by dhonus** [comment]
I updated the description to also mention intel. Thank you for verifying :)
